ONE_DAY = '1D'
TWO_DAY = '2D'
THREE_DAY = '3D'
FIVE_DAY = '5D'

ONE_WEEK = '1W'
TWO_WEEK = '2W'
THREE_WEEK = '3W'

ONE_MONTH = '1M'
THREE_MONTH = '3M'
SIX_MONTH = '6M'
TWELVE_MONTH = '12M'

PRESETS=[ONE_DAY, TWO_DAY, THREE_DAY, FIVE_DAY, ONE_WEEK, TWO_WEEK, THREE_WEEK, ONE_MONTH, THREE_MONTH, SIX_MONTH, TWELVE_MONTH]